version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: pip install git+https://github.com/tiptapinc/ZeroG
          name: Install Zerog package
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m pytest tests --cov=spacewalk --cov-report term-missing --cov-config=.coveragerc
          name: Run Unit Tests

workflows:
  main:
    jobs:
      - build-and-test