version: 2.1

orbs:
  python: circleci/python@0.3.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: wget http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-6-amd64.deb
          name: Get Couchbase Release Repo
      - run:
          command: sudo dpkg -i couchbase-release-1.0-6-amd64.deb
          name: Install Couchbase Release Repo
      - run:
          command: sudo apt-get update
          name: Refresh the APT cache
      - run:
          command: sudo apt-get install libcouchbase-dev libcouchbase2-bin build-essential
          name: Install libcouchbase
      - run:
          command: pip install git+https://github.com/tiptapinc/ZeroG
          name: Install Zerog package
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m pytest tests --cov=spacewalk --cov-report term-missing --cov-config=.coveragerc
          name: Run Unit Tests

workflows:
  main:
    jobs:
      - build-and-test